name: publish to test-drafts website

on:
  workflow_dispatch:
    branches:
      - main  # Set a branch to deploy

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        run: hugo --buildDrafts --minify --baseURL "https://roman-gardens.github.io/test-drafts/"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY_TEST_B }}
          EXTERNAL_REPOSITORY: roman-gardens/test-drafts
          PUBLISH_BRANCH: main
          PUBLISH_DIR: ./docs
        with:
          emptyCommits: false
          commitMessage: ${{ github.event.head_commit.message }}

